#pragma once

// Prefixed with VT_ to avoid colliding with VMCALL_* macros in KernelCommon.VmxHelper.h.
// Numeric order matches UnrealVTDbg vm_call_reasons.
enum vt_vm_call_reasons
{
	VT_VMCALL_TEST,
	VT_VMCALL_VMXOFF,
	VT_VMCALL_EPT_CC_HOOK,
	VT_VMCALL_EPT_INT1_HOOK,
	VT_VMCALL_EPT_RIP_HOOK,
	VT_VMCALL_EPT_HOOK_FUNCTION,
	VT_VMCALL_EPT_UNHOOK_FUNCTION,
	VT_VMCALL_INVEPT_CONTEXT,
	VT_VMCALL_DUMP_POOL_MANAGER,
	VT_VMCALL_DUMP_VMCS_STATE,
	VT_VMCALL_HIDE_HV_PRESENCE,
	VT_VMCALL_UNHIDE_HV_PRESENCE,
	VT_VMCALL_HIDE_SOFTWARE_BREAKPOINT,
	VT_VMCALL_READ_SOFTWARE_BREAKPOINT,
	VT_VMCALL_READ_EPT_FAKE_PAGE_MEMORY,
	VT_VMCALL_WATCH_WRITES,
	VT_VMCALL_WATCH_READS,
	VT_VMCALL_WATCH_EXECUTES,
	VT_VMCALL_WATCH_DELETE,
	VT_VMCALL_GET_BREAKPOINT,
	VT_VMCALL_INIT_OFFSET,
};
