#pragma once

#define PASSWORD1 0x76543210
#define PASSWORD2 0xfedcba98
#define PASSWORD3 0x90909090

//=========================================
#define IOCTL_WEDEBUG_Test                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WEDEBUG_GetProcessCr3         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WEDEBUG_InitSymbols           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WEDEBUG_DbgkInit              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)